name: generate animation

on:
  schedule:
    - cron: "0 */1 * * *"  
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: generate github-contribution-grid-snake.svg (light only)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Monkshark
          outputs: |
            dist/github-contribution-grid-snake.svg?palette=github-light

      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
